version: "3"
services:
  srs-benchmark:
    build: 
      context: .
      dockerfile: Dockerfile
    image: srs-benchmark-tool
    container_name: srs-benchmark-tool
  netdata:
    image: firehol/netdata
    ports: 
      - 19999:19999/tcp
    container_name: netdata