version: "3"
services:
  srs-benchmark:
    build: 
      context: .
      dockerfile: Dockerfile-benchmark
    image: srs-benchmark-tool
    container_name: srs-benchmark-tool
    volumes:
      - ./benchmark-resource:/home/benchmark-resource
    tty: true
    networks:
      - srs-benchmark
  ossrs:
    build:
      context: .
      dockerfile: Dockerfile-ossrs
    image: srs-benchmark-ossrs
    container_name: srs-benchmark-ossrs
    volumes:
      - ./srs-conf:/opt/srs/trunk/conf
    working_dir: /opt/srs/trunk
    tty: true
    networks:
      - srs-benchmark
    # volumes:
      # - 
networks:
  srs-benchmark:
    driver: bridge